=== nizhm/webpack-es-learning/src/browser-env/XML/xsd/basic.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.w3schools.com"
           xmlns="https://www.w3schools.com"
           elementFormDefault="qualified">

    <xs:element name="note">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="to" type="xs:string"/>
                <xs:element name="from" type="xs:string"/>
                <xs:element name="heading" type="xs:string"/>
                <xs:element name="body" type="xs:string"/>
                <xs:element name="age" type="xs:integer"></xs:element>
                <xs:element name="color" type="xs:string" default="red"></xs:element>
                <xs:element name="colour" type="xs:string" fixed="blue"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== nizhm/webpack-es-learning/src/browser-env/XML/basic.xml
<?xml version="1.0" encoding="utf-8"?>
<note
    xmlns="https://www.w3schools.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.w3schools.com xsd/basic.xsd"
>
    <to>Tove</to>
    <from>Jani</from>
    <heading>Reminder</heading>
    <body>Don't forget me this weekend!</body>
    <age>20</age>
    <color></color>
    <colour></colour>
</note>
